spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hibernate_learning
    username: admin
    password: admin123

  jpa:
    hibernate:
      ddl-auto: update  # ou 'create', 'create-drop', 'validate'
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: SCHOOL

app:
  datasource:
    url: jdbc:postgresql://localhost:5432/hibernate_learning
    username: admin
    password: admin123
    driver: org.postgresql.Driver
    dialect: org.hibernate.dialect.PostgreSQLDialect
    hbm2ddl: update