spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hibernate_learning
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # ou 'create', 'create-drop', 'validate'
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: SCHOOL